### ISSUE TITLE
UX Improvement - better management of placeholder location

### ISSUE THREAD

**Issue by mfeherpataky** [lukasoppermann/html5sortable#394]
My users and I, really appreciate a placeholder in the place of a valid dropTarget. Styling is super-easy, and assigning the dimensions of the dragItem to the placeholder is super useful feature.

Today placeholders are placed when a dragItem enters a valid dropTarget, but not removed when the dragItem leaves the location. This leads to a user-confusion as where the dragItem would be dropped when released once it is somewhere outside of a valid dropTarget - would it be the last valid location (where the placeholder still is), would it be the initial location? Finally it is the original location, but it is nowhere clear to first time users.

I propose a following Usability Improvement:
- [ ] First step would be to remove placeholders when a dragItem is no longer over a valid dropTarget. 
- [ ] Finally the placeholder should go back to the originalContainer and its initial index (unless a dragItem was cloned from a copy-only list).

**Comment by lukasoppermann** [comment]
Hey @mfeherpataky, I totally agree. I would like to at some point also allow for the possibility to remove elements when dragged outside a list and dropped without a valid target. But this is probably to much to consider now.

However, I would really appreciate those improvements.

**Comment by kaffarell** [comment]
I think this issue is resolved...
Can I close it @lukasoppermann ?

**Comment by lukasoppermann** [comment]
Sadly it is not resolved. Maybe we could split this out into 2 different issues and add a better explanation to them.

**Comment by lukasoppermann** [comment]
Closing this in favour of https://github.com/lukasoppermann/html5sortable/issues/553 and https://github.com/lukasoppermann/html5sortable/issues/554
